# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'CitySearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SnapKit'

  target 'CitySearchTests' do
    inherit! :search_paths
    
    pod 'RxSwift'
    pod 'RxCocoa'
  end

  target 'CitySearchUITests' do
    # Pods for testing
  end

end
