# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

def rx_swift
  pod 'RxSwift', '~> 6.5.0'
end

def rx_cocoa
  pod 'RxCocoa', '~> 6.5.0'
end

def snap_kit
  pod 'SnapKit'
end

def test_pods
  rx_cocoa
  rx_swift
end

target 'CitySearch' do
  use_frameworks!
  rx_cocoa
  rx_swift
  snap_kit

  target 'CitySearchTests' do
    inherit! :search_paths
    test_pods
  end
end

target 'Domain' do
  use_frameworks!
  rx_swift
end

target 'NetworkPlatform' do
    use_frameworks!
    rx_swift
    rx_cocoa
end
